name: Deploy to Heroku

on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Maven build/package
        run: mvn -B package --file pom.xml

      - name: Docker image push
        run: heroku container:push web --app springboot-intens

      - name: Docker image release
        run: heroku container:release web --app springboot-intens
